# TCL File Generated by Component Editor 8.1
# Fri Jul 17 18:22:43 CEST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | MMslaveint "MMslaveint" v1.0
# | null 2009.07.17.18:22:43
# | 
# | 
# | C:/Stefano/A-work/stx3/n2mdio1a_dk/MMslaveint.vhd
# | 
# |    ./MMslaveint.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module MMslaveint
# | 
set_module_property NAME MMslaveint
set_module_property VERSION 1.0
set_module_property GROUP Custom
set_module_property DISPLAY_NAME MMslaveint
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.numeric_std.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE MMslaveint.vhd
set_module_property TOP_LEVEL_HDL_MODULE MMslaveint
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file MMslaveint.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter ADDRSIZE NATURAL 4
set_parameter_property ADDRSIZE DISPLAY_NAME ADDRSIZE
set_parameter_property ADDRSIZE UNITS None
set_parameter_property ADDRSIZE AFFECTS_ELABORATION true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock ptfSchematicName ""

add_interface_port clock clk clk Input 1
add_interface_port clock rst reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point slave
# | 
add_interface slave avalon end
set_interface_property slave addressAlignment DYNAMIC
set_interface_property slave addressSpan 4
set_interface_property slave bridgesToMaster ""
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave holdTime 0
set_interface_property slave isMemoryDevice false
set_interface_property slave isNonVolatileStorage false
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 1
set_interface_property slave minimumUninterruptedRunLength 1
set_interface_property slave printableDevice false
set_interface_property slave readLatency 0
set_interface_property slave readWaitStates 0
set_interface_property slave readWaitTime 0
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0

set_interface_property slave ASSOCIATED_CLOCK clock

add_interface_port slave mmaddress address Input -1
add_interface_port slave mmread read Input 1
add_interface_port slave mmwrite write Input 1
add_interface_port slave mmwritedata writedata Input 32
add_interface_port slave mmreaddatavalid readdatavalid Output 1
add_interface_port slave mmwaitrequest waitrequest Output 1
add_interface_port slave mmreaddata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point export
# | 
add_interface export conduit end

set_interface_property export ASSOCIATED_CLOCK clock

add_interface_port export s_readdata export Input 32
add_interface_port export s_readdatavalid export Input 1
add_interface_port export s_waitrequest export Input 1
add_interface_port export s_clk export Output 1
add_interface_port export s_rst export Output 1
add_interface_port export s_address export Output -1
add_interface_port export s_read export Output 1
add_interface_port export s_write export Output 1
add_interface_port export s_writedata export Output 32
# | 
# +-----------------------------------
